### PR TITLE
Toast Components

### PR DESCRIPTION
**Pull request by devanpatel1008**
## [LEVEL]/[COMPONENT]

**TASK**: 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Only
- [ ] Refactor

### CODE REVIEW

**Review by AmitMirgal — COMMENTED** [review]
any reason we are planning to use react-toastify? @devanpatel1008

**Comment by AmitMirgal** [comment]
you can take a look at https://github.com/eatozee/nftoupon/pull/5 PR... this PR using react-hot-toast... We have decided to use react-hot-toast please let me know if we have a different plan 😺

**Comment by devanpatel1008** [comment]
> any reason we are planning to use react-toastify? @devanpatel1008
I liked the ui for react toastify better than hot toast but I will change it to hot toast right away I didnt knew we were planning to use react hot toast for anything else.

**Comment by AmitMirgal** [comment]
not required anymore

**Pull request closed without merging**
